### ISSUE TITLE
Bad ggpack when writing a new one

### ISSUE THREAD

**Issue by scemino** [fzipp/gg#1]
With Thimbleweed Park v1421.958 on MacOS Catalina v10.15.6 (19G2021)
If I dump all the resources to a directory and repack it to a new .ggpack (without modifying the files), and I replace the ThimbleweedPark.ggpack1 file, I have this error:
`Boot.bnut:1: end of statement expected (; or lf)`

This is my command:
`./ggpack -create "resources/*" ThimbleweedPark.ggpack1`

**Comment by fzipp** [comment]
Thanks for the bug report. It should be fixed now. Let me know if there are still problems.

**Comment by scemino** [comment]
It works great now thanks 👏
